// flow-typed signature: f2d94a0d50c8f2e02ad32669cef2d591
// flow-typed version: <<STUB>>/argparse_v^1.0.9/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'argparse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'argparse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'argparse/lib/action_container' {
  declare module.exports: any;
}

declare module 'argparse/lib/action' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/append' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/append/constant' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/count' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/help' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/store' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/store/constant' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/store/false' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/store/true' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/subparsers' {
  declare module.exports: any;
}

declare module 'argparse/lib/action/version' {
  declare module.exports: any;
}

declare module 'argparse/lib/argparse' {
  declare module.exports: any;
}

declare module 'argparse/lib/argument_parser' {
  declare module.exports: any;
}

declare module 'argparse/lib/argument/error' {
  declare module.exports: any;
}

declare module 'argparse/lib/argument/exclusive' {
  declare module.exports: any;
}

declare module 'argparse/lib/argument/group' {
  declare module.exports: any;
}

declare module 'argparse/lib/const' {
  declare module.exports: any;
}

declare module 'argparse/lib/help/added_formatters' {
  declare module.exports: any;
}

declare module 'argparse/lib/help/formatter' {
  declare module.exports: any;
}

declare module 'argparse/lib/namespace' {
  declare module.exports: any;
}

declare module 'argparse/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'argparse/index' {
  declare module.exports: $Exports<'argparse'>;
}
declare module 'argparse/index.js' {
  declare module.exports: $Exports<'argparse'>;
}
declare module 'argparse/lib/action_container.js' {
  declare module.exports: $Exports<'argparse/lib/action_container'>;
}
declare module 'argparse/lib/action.js' {
  declare module.exports: $Exports<'argparse/lib/action'>;
}
declare module 'argparse/lib/action/append.js' {
  declare module.exports: $Exports<'argparse/lib/action/append'>;
}
declare module 'argparse/lib/action/append/constant.js' {
  declare module.exports: $Exports<'argparse/lib/action/append/constant'>;
}
declare module 'argparse/lib/action/count.js' {
  declare module.exports: $Exports<'argparse/lib/action/count'>;
}
declare module 'argparse/lib/action/help.js' {
  declare module.exports: $Exports<'argparse/lib/action/help'>;
}
declare module 'argparse/lib/action/store.js' {
  declare module.exports: $Exports<'argparse/lib/action/store'>;
}
declare module 'argparse/lib/action/store/constant.js' {
  declare module.exports: $Exports<'argparse/lib/action/store/constant'>;
}
declare module 'argparse/lib/action/store/false.js' {
  declare module.exports: $Exports<'argparse/lib/action/store/false'>;
}
declare module 'argparse/lib/action/store/true.js' {
  declare module.exports: $Exports<'argparse/lib/action/store/true'>;
}
declare module 'argparse/lib/action/subparsers.js' {
  declare module.exports: $Exports<'argparse/lib/action/subparsers'>;
}
declare module 'argparse/lib/action/version.js' {
  declare module.exports: $Exports<'argparse/lib/action/version'>;
}
declare module 'argparse/lib/argparse.js' {
  declare module.exports: $Exports<'argparse/lib/argparse'>;
}
declare module 'argparse/lib/argument_parser.js' {
  declare module.exports: $Exports<'argparse/lib/argument_parser'>;
}
declare module 'argparse/lib/argument/error.js' {
  declare module.exports: $Exports<'argparse/lib/argument/error'>;
}
declare module 'argparse/lib/argument/exclusive.js' {
  declare module.exports: $Exports<'argparse/lib/argument/exclusive'>;
}
declare module 'argparse/lib/argument/group.js' {
  declare module.exports: $Exports<'argparse/lib/argument/group'>;
}
declare module 'argparse/lib/const.js' {
  declare module.exports: $Exports<'argparse/lib/const'>;
}
declare module 'argparse/lib/help/added_formatters.js' {
  declare module.exports: $Exports<'argparse/lib/help/added_formatters'>;
}
declare module 'argparse/lib/help/formatter.js' {
  declare module.exports: $Exports<'argparse/lib/help/formatter'>;
}
declare module 'argparse/lib/namespace.js' {
  declare module.exports: $Exports<'argparse/lib/namespace'>;
}
declare module 'argparse/lib/utils.js' {
  declare module.exports: $Exports<'argparse/lib/utils'>;
}
