// flow-typed signature: abc93591c037ce1f892762dc00c99a52
// flow-typed version: <<STUB>>/array-includes_v^3.0.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-includes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-includes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'array-includes/implementation' {
  declare module.exports: any;
}

declare module 'array-includes/polyfill' {
  declare module.exports: any;
}

declare module 'array-includes/shim' {
  declare module.exports: any;
}

declare module 'array-includes/test/index' {
  declare module.exports: any;
}

declare module 'array-includes/test/shimmed' {
  declare module.exports: any;
}

declare module 'array-includes/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'array-includes/implementation.js' {
  declare module.exports: $Exports<'array-includes/implementation'>;
}
declare module 'array-includes/index' {
  declare module.exports: $Exports<'array-includes'>;
}
declare module 'array-includes/index.js' {
  declare module.exports: $Exports<'array-includes'>;
}
declare module 'array-includes/polyfill.js' {
  declare module.exports: $Exports<'array-includes/polyfill'>;
}
declare module 'array-includes/shim.js' {
  declare module.exports: $Exports<'array-includes/shim'>;
}
declare module 'array-includes/test/index.js' {
  declare module.exports: $Exports<'array-includes/test/index'>;
}
declare module 'array-includes/test/shimmed.js' {
  declare module.exports: $Exports<'array-includes/test/shimmed'>;
}
declare module 'array-includes/test/tests.js' {
  declare module.exports: $Exports<'array-includes/test/tests'>;
}
