// flow-typed signature: 5468dbd806eae38e0c14e04e4f3e33c9
// flow-typed version: <<STUB>>/eslint-plugin-eslint-comments_v^1.0.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-eslint-comments'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-eslint-comments' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-eslint-comments/lib/disabled-area' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-comments/lib/rules/disable-enable-pair' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-comments/lib/rules/no-duplicate-disable' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-comments/lib/rules/no-unlimited-disable' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-comments/lib/rules/no-unused-disable' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-comments/lib/rules/no-unused-enable' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-comments/lib/rules/no-use' {
  declare module.exports: any;
}

declare module 'eslint-plugin-eslint-comments/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-eslint-comments/index' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments'>;
}
declare module 'eslint-plugin-eslint-comments/index.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments'>;
}
declare module 'eslint-plugin-eslint-comments/lib/disabled-area.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments/lib/disabled-area'>;
}
declare module 'eslint-plugin-eslint-comments/lib/rules/disable-enable-pair.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments/lib/rules/disable-enable-pair'>;
}
declare module 'eslint-plugin-eslint-comments/lib/rules/no-duplicate-disable.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments/lib/rules/no-duplicate-disable'>;
}
declare module 'eslint-plugin-eslint-comments/lib/rules/no-unlimited-disable.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments/lib/rules/no-unlimited-disable'>;
}
declare module 'eslint-plugin-eslint-comments/lib/rules/no-unused-disable.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments/lib/rules/no-unused-disable'>;
}
declare module 'eslint-plugin-eslint-comments/lib/rules/no-unused-enable.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments/lib/rules/no-unused-enable'>;
}
declare module 'eslint-plugin-eslint-comments/lib/rules/no-use.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments/lib/rules/no-use'>;
}
declare module 'eslint-plugin-eslint-comments/lib/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-eslint-comments/lib/utils'>;
}
