// flow-typed signature: ebf69fe3cca81c7cd9548ee605a8887a
// flow-typed version: <<STUB>>/flow-annotation-check_v^1.1.2/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-annotation-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-annotation-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-annotation-check/bin/flow-annotation-check' {
  declare module.exports: any;
}

declare module 'flow-annotation-check/lib/cli' {
  declare module.exports: any;
}

declare module 'flow-annotation-check/lib/core' {
  declare module.exports: any;
}

declare module 'flow-annotation-check/lib/flow-annotation-check' {
  declare module.exports: any;
}

declare module 'flow-annotation-check/lib/flow' {
  declare module.exports: any;
}

declare module 'flow-annotation-check/lib/globsToFileList' {
  declare module.exports: any;
}

declare module 'flow-annotation-check/lib/isValidFlowStatus' {
  declare module.exports: any;
}

declare module 'flow-annotation-check/lib/promisified' {
  declare module.exports: any;
}

declare module 'flow-annotation-check/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-annotation-check/bin/flow-annotation-check.js' {
  declare module.exports: $Exports<'flow-annotation-check/bin/flow-annotation-check'>;
}
declare module 'flow-annotation-check/lib/cli.js' {
  declare module.exports: $Exports<'flow-annotation-check/lib/cli'>;
}
declare module 'flow-annotation-check/lib/core.js' {
  declare module.exports: $Exports<'flow-annotation-check/lib/core'>;
}
declare module 'flow-annotation-check/lib/flow-annotation-check.js' {
  declare module.exports: $Exports<'flow-annotation-check/lib/flow-annotation-check'>;
}
declare module 'flow-annotation-check/lib/flow.js' {
  declare module.exports: $Exports<'flow-annotation-check/lib/flow'>;
}
declare module 'flow-annotation-check/lib/globsToFileList.js' {
  declare module.exports: $Exports<'flow-annotation-check/lib/globsToFileList'>;
}
declare module 'flow-annotation-check/lib/isValidFlowStatus.js' {
  declare module.exports: $Exports<'flow-annotation-check/lib/isValidFlowStatus'>;
}
declare module 'flow-annotation-check/lib/promisified.js' {
  declare module.exports: $Exports<'flow-annotation-check/lib/promisified'>;
}
declare module 'flow-annotation-check/lib/types.js' {
  declare module.exports: $Exports<'flow-annotation-check/lib/types'>;
}
