// flow-typed signature: 76fee7a2f201fa4bfa1aca122e842d08
// flow-typed version: <<STUB>>/load-pkg_v^3.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'load-pkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'load-pkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'load-pkg/index' {
  declare module.exports: $Exports<'load-pkg'>;
}
declare module 'load-pkg/index.js' {
  declare module.exports: $Exports<'load-pkg'>;
}
