// flow-typed signature: 91dd4d2e37ebbcbddb10e622be8e1931
// flow-typed version: <<STUB>>/markdown-spellcheck_v^1.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-spellcheck'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-spellcheck' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-spellcheck/es5/cli-interactive' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/cli' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/context' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/filters' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/index' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/markdown-parser' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/multi-file-processor' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/report-generator' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/spell-config' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/spellcheck' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/tracking-replacement' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/word-parser' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/word-replacer' {
  declare module.exports: any;
}

declare module 'markdown-spellcheck/es5/write-corrections' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-spellcheck/es5/cli-interactive.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/cli-interactive'>;
}
declare module 'markdown-spellcheck/es5/cli.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/cli'>;
}
declare module 'markdown-spellcheck/es5/context.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/context'>;
}
declare module 'markdown-spellcheck/es5/filters.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/filters'>;
}
declare module 'markdown-spellcheck/es5/index.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/index'>;
}
declare module 'markdown-spellcheck/es5/markdown-parser.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/markdown-parser'>;
}
declare module 'markdown-spellcheck/es5/multi-file-processor.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/multi-file-processor'>;
}
declare module 'markdown-spellcheck/es5/report-generator.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/report-generator'>;
}
declare module 'markdown-spellcheck/es5/spell-config.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/spell-config'>;
}
declare module 'markdown-spellcheck/es5/spellcheck.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/spellcheck'>;
}
declare module 'markdown-spellcheck/es5/tracking-replacement.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/tracking-replacement'>;
}
declare module 'markdown-spellcheck/es5/word-parser.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/word-parser'>;
}
declare module 'markdown-spellcheck/es5/word-replacer.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/word-replacer'>;
}
declare module 'markdown-spellcheck/es5/write-corrections.js' {
  declare module.exports: $Exports<'markdown-spellcheck/es5/write-corrections'>;
}
