// flow-typed signature: a7f126f938dcb87433e70ca4ed2786c9
// flow-typed version: <<STUB>>/object.values_v^1.0.4/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object.values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object.values' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object.values/implementation' {
  declare module.exports: any;
}

declare module 'object.values/polyfill' {
  declare module.exports: any;
}

declare module 'object.values/shim' {
  declare module.exports: any;
}

declare module 'object.values/test/index' {
  declare module.exports: any;
}

declare module 'object.values/test/shimmed' {
  declare module.exports: any;
}

declare module 'object.values/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object.values/implementation.js' {
  declare module.exports: $Exports<'object.values/implementation'>;
}
declare module 'object.values/index' {
  declare module.exports: $Exports<'object.values'>;
}
declare module 'object.values/index.js' {
  declare module.exports: $Exports<'object.values'>;
}
declare module 'object.values/polyfill.js' {
  declare module.exports: $Exports<'object.values/polyfill'>;
}
declare module 'object.values/shim.js' {
  declare module.exports: $Exports<'object.values/shim'>;
}
declare module 'object.values/test/index.js' {
  declare module.exports: $Exports<'object.values/test/index'>;
}
declare module 'object.values/test/shimmed.js' {
  declare module.exports: $Exports<'object.values/test/shimmed'>;
}
declare module 'object.values/test/tests.js' {
  declare module.exports: $Exports<'object.values/test/tests'>;
}
