// flow-typed signature: 218f434475b66aa495b52598a7baf342
// flow-typed version: <<STUB>>/storyshots_v^3.2.2/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storyshots'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'storyshots' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storyshots/dist/cli' {
  declare module.exports: any;
}

declare module 'storyshots/dist/default_config/loaders' {
  declare module.exports: any;
}

declare module 'storyshots/dist/default_config/polyfills' {
  declare module.exports: any;
}

declare module 'storyshots/dist/index' {
  declare module.exports: any;
}

declare module 'storyshots/dist/require_context' {
  declare module.exports: any;
}

declare module 'storyshots/dist/storybook-channel-mock' {
  declare module.exports: any;
}

declare module 'storyshots/dist/test_runner/index' {
  declare module.exports: any;
}

declare module 'storyshots/dist/test_runner/snapshot_runner' {
  declare module.exports: any;
}

declare module 'storyshots/dist/util' {
  declare module.exports: any;
}

declare module 'storyshots/stories/__test__/storyshots.test' {
  declare module.exports: any;
}

declare module 'storyshots/stories/directly_required/Button' {
  declare module.exports: any;
}

declare module 'storyshots/stories/directly_required/index' {
  declare module.exports: any;
}

declare module 'storyshots/stories/required_with_context/Button' {
  declare module.exports: any;
}

declare module 'storyshots/stories/required_with_context/Button.stories' {
  declare module.exports: any;
}

declare module 'storyshots/stories/required_with_context/Welcome' {
  declare module.exports: any;
}

declare module 'storyshots/stories/required_with_context/Welcome.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storyshots/dist/cli.js' {
  declare module.exports: $Exports<'storyshots/dist/cli'>;
}
declare module 'storyshots/dist/default_config/loaders.js' {
  declare module.exports: $Exports<'storyshots/dist/default_config/loaders'>;
}
declare module 'storyshots/dist/default_config/polyfills.js' {
  declare module.exports: $Exports<'storyshots/dist/default_config/polyfills'>;
}
declare module 'storyshots/dist/index.js' {
  declare module.exports: $Exports<'storyshots/dist/index'>;
}
declare module 'storyshots/dist/require_context.js' {
  declare module.exports: $Exports<'storyshots/dist/require_context'>;
}
declare module 'storyshots/dist/storybook-channel-mock.js' {
  declare module.exports: $Exports<'storyshots/dist/storybook-channel-mock'>;
}
declare module 'storyshots/dist/test_runner/index.js' {
  declare module.exports: $Exports<'storyshots/dist/test_runner/index'>;
}
declare module 'storyshots/dist/test_runner/snapshot_runner.js' {
  declare module.exports: $Exports<'storyshots/dist/test_runner/snapshot_runner'>;
}
declare module 'storyshots/dist/util.js' {
  declare module.exports: $Exports<'storyshots/dist/util'>;
}
declare module 'storyshots/stories/__test__/storyshots.test.js' {
  declare module.exports: $Exports<'storyshots/stories/__test__/storyshots.test'>;
}
declare module 'storyshots/stories/directly_required/Button.js' {
  declare module.exports: $Exports<'storyshots/stories/directly_required/Button'>;
}
declare module 'storyshots/stories/directly_required/index.js' {
  declare module.exports: $Exports<'storyshots/stories/directly_required/index'>;
}
declare module 'storyshots/stories/required_with_context/Button.js' {
  declare module.exports: $Exports<'storyshots/stories/required_with_context/Button'>;
}
declare module 'storyshots/stories/required_with_context/Button.stories.js' {
  declare module.exports: $Exports<'storyshots/stories/required_with_context/Button.stories'>;
}
declare module 'storyshots/stories/required_with_context/Welcome.js' {
  declare module.exports: $Exports<'storyshots/stories/required_with_context/Welcome'>;
}
declare module 'storyshots/stories/required_with_context/Welcome.stories.js' {
  declare module.exports: $Exports<'storyshots/stories/required_with_context/Welcome.stories'>;
}
