// flow-typed signature: 1a1c1f8fc2d8a853d4000c74293d82d4
// flow-typed version: <<STUB>>/@kadira/storybook_v^2.35.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storybook/addons' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/manager/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/manager/preview' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/manager/provider' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/actions' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/client_api' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/config_api' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/error_display' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/init' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/reducer' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/render' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/client/preview/story_store' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/addons' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/babel_config' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/build' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/babel' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/babel.prod' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/defaults/webpack.config' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/globals' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/polyfills' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/utils' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/WatchMissingNodeModulesPlugin' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/webpack.config' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/config/webpack.config.prod' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/iframe.html' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/index.html' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/index' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/middleware' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/track_usage' {
  declare module.exports: any;
}

declare module '@kadira/storybook/dist/server/utils' {
  declare module.exports: any;
}

declare module '@kadira/storybook/scripts/mocha_runner' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/storybook/addons.js' {
  declare module.exports: $Exports<'@kadira/storybook/addons'>;
}
declare module '@kadira/storybook/dist/client/index.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/index'>;
}
declare module '@kadira/storybook/dist/client/manager/index.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/manager/index'>;
}
declare module '@kadira/storybook/dist/client/manager/preview.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/manager/preview'>;
}
declare module '@kadira/storybook/dist/client/manager/provider.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/manager/provider'>;
}
declare module '@kadira/storybook/dist/client/preview/actions.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/actions'>;
}
declare module '@kadira/storybook/dist/client/preview/client_api.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/client_api'>;
}
declare module '@kadira/storybook/dist/client/preview/config_api.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/config_api'>;
}
declare module '@kadira/storybook/dist/client/preview/error_display.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/error_display'>;
}
declare module '@kadira/storybook/dist/client/preview/index.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/index'>;
}
declare module '@kadira/storybook/dist/client/preview/init.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/init'>;
}
declare module '@kadira/storybook/dist/client/preview/reducer.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/reducer'>;
}
declare module '@kadira/storybook/dist/client/preview/render.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/render'>;
}
declare module '@kadira/storybook/dist/client/preview/story_store.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/client/preview/story_store'>;
}
declare module '@kadira/storybook/dist/server/addons.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/addons'>;
}
declare module '@kadira/storybook/dist/server/babel_config.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/babel_config'>;
}
declare module '@kadira/storybook/dist/server/build.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/build'>;
}
declare module '@kadira/storybook/dist/server/config.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config'>;
}
declare module '@kadira/storybook/dist/server/config/babel.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/babel'>;
}
declare module '@kadira/storybook/dist/server/config/babel.prod.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/babel.prod'>;
}
declare module '@kadira/storybook/dist/server/config/defaults/webpack.config.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/defaults/webpack.config'>;
}
declare module '@kadira/storybook/dist/server/config/globals.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/globals'>;
}
declare module '@kadira/storybook/dist/server/config/polyfills.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/polyfills'>;
}
declare module '@kadira/storybook/dist/server/config/utils.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/utils'>;
}
declare module '@kadira/storybook/dist/server/config/WatchMissingNodeModulesPlugin.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/WatchMissingNodeModulesPlugin'>;
}
declare module '@kadira/storybook/dist/server/config/webpack.config.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/webpack.config'>;
}
declare module '@kadira/storybook/dist/server/config/webpack.config.prod.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/config/webpack.config.prod'>;
}
declare module '@kadira/storybook/dist/server/iframe.html.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/iframe.html'>;
}
declare module '@kadira/storybook/dist/server/index.html.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/index.html'>;
}
declare module '@kadira/storybook/dist/server/index.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/index'>;
}
declare module '@kadira/storybook/dist/server/middleware.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/middleware'>;
}
declare module '@kadira/storybook/dist/server/track_usage.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/track_usage'>;
}
declare module '@kadira/storybook/dist/server/utils.js' {
  declare module.exports: $Exports<'@kadira/storybook/dist/server/utils'>;
}
declare module '@kadira/storybook/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'@kadira/storybook/scripts/mocha_runner'>;
}
